### ISSUE TITLE
Help with Captions and a small issue

### ISSUE THREAD

**Issue by MyPC8MyBrain** [akizor/PhotoSwipe-Gallery-Improvement#1]
thank you for your work on this improved Photo Swipe revision!
it is exactly what i was missing to complete my project,
im not a web developer; i can make sense of the basic; but this is over my head,

Ive been playing around with your work recently,
having one issue and a please help requests :) ,

is it possible to get captions to show along with share tab?

for some reason im getting a double count in gallery counter!
my test page can be found here if you don't mind having a looksy 
http://xpertnetworking.com/slider/slide.html
(if i remove `<DIV class="owl-carousel owl-theme">` counter works fine!)

in my case i am trying to marry your improved Photo Swipe with 
OwlCarousel2 https://owlcarousel2.github.io/OwlCarousel2/
ideally each carousel slot will hold one gallery image,
its all working based on your template; 
accept for the two issues i mentioned above i am looking to solve,

any help is greatly appreciated 
TIA
Chris

**Comment by akizor** [comment]
@MyPC8MyBrain i'm getting a 500 error on that page.

**Comment by MyPC8MyBrain** [comment]
Thank you Akizor :)
i found most of what I was looking for by now; 
ended up redoing code; im very happy with my current outcome,
had to custom fix Owl code to work with Photoswipe; but i think i managed it,
you can view my new album here http://nightenvironment.com/dev/slider/slider.html
(use mouse scroll or swipe on the first carousel; pick a slide and click it Photoswipe will trigger the right image,
id love to hear your thought :)

**Comment by akizor** [comment]
@MyPC8MyBrain Looks very good indeed. I really like it. Congrats.
Probably sometime, i will add owl carousel support directly into demo. Thanks for idea.

**Comment by MyPC8MyBrain** [comment]
Thank you Daniel :)
still working on minor tweaks,
had some indexing issue with Owl, but its all behind us now,
a more updated and integrated version can be found here http://xpertnetworking.com/coding4/

ATB
Chris
